/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app/workspaces'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news.index'
import { Route as AppWorkspacesNewRouteImport } from './routes/_app/workspaces.new'
import { Route as AppSettingsCategoryRouteImport } from './routes/_app/settings.$category'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects.new'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as AppNewsNewsIdRouteImport } from './routes/_app/news.$newsId'
import { Route as AppWorkspacesWorkspaceIdIndexRouteImport } from './routes/_app/workspaces.$workspaceId.index'
import { Route as AppWorkspacesWorkspaceIdSettingsRouteImport } from './routes/_app/workspaces.$workspaceId.settings'
import { Route as AppWorkspacesWorkspaceIdSessionsIndexRouteImport } from './routes/_app/workspaces.$workspaceId.sessions.index'
import { Route as AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport } from './routes/_app/workspaces.$workspaceId.sessions.$sessionId'

const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspacesRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppWorkspacesNewRoute = AppWorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppWorkspacesRoute,
} as any)
const AppSettingsCategoryRoute = AppSettingsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppNewsNewsIdRoute = AppNewsNewsIdRouteImport.update({
  id: '/$newsId',
  path: '/$newsId',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppWorkspacesWorkspaceIdIndexRoute =
  AppWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/$workspaceId/',
    path: '/$workspaceId/',
    getParentRoute: () => AppWorkspacesRoute,
  } as any)
const AppWorkspacesWorkspaceIdSettingsRoute =
  AppWorkspacesWorkspaceIdSettingsRouteImport.update({
    id: '/$workspaceId/settings',
    path: '/$workspaceId/settings',
    getParentRoute: () => AppWorkspacesRoute,
  } as any)
const AppWorkspacesWorkspaceIdSessionsIndexRoute =
  AppWorkspacesWorkspaceIdSessionsIndexRouteImport.update({
    id: '/$workspaceId/sessions/',
    path: '/$workspaceId/sessions/',
    getParentRoute: () => AppWorkspacesRoute,
  } as any)
const AppWorkspacesWorkspaceIdSessionsSessionIdRoute =
  AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport.update({
    id: '/$workspaceId/sessions/$sessionId',
    path: '/$workspaceId/sessions/$sessionId',
    getParentRoute: () => AppWorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/automations': typeof AppAutomationsRoute
  '/connections': typeof AppConnectionsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/news': typeof AppNewsRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/workspaces': typeof AppWorkspacesRouteWithChildren
  '/news/$newsId': typeof AppNewsNewsIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/$category': typeof AppSettingsCategoryRoute
  '/workspaces/new': typeof AppWorkspacesNewRoute
  '/news/': typeof AppNewsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AppWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/sessions/': typeof AppWorkspacesWorkspaceIdSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/automations': typeof AppAutomationsRoute
  '/connections': typeof AppConnectionsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/news/$newsId': typeof AppNewsNewsIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/settings/$category': typeof AppSettingsCategoryRoute
  '/workspaces/new': typeof AppWorkspacesNewRoute
  '/news': typeof AppNewsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AppWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/sessions': typeof AppWorkspacesWorkspaceIdSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/news': typeof AppNewsRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/workspaces': typeof AppWorkspacesRouteWithChildren
  '/_app/news/$newsId': typeof AppNewsNewsIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/settings/$category': typeof AppSettingsCategoryRoute
  '/_app/workspaces/new': typeof AppWorkspacesNewRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/workspaces/$workspaceId/settings': typeof AppWorkspacesWorkspaceIdSettingsRoute
  '/_app/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/_app/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
  '/_app/workspaces/$workspaceId/sessions/': typeof AppWorkspacesWorkspaceIdSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/migration'
    | '/automations'
    | '/connections'
    | '/marketplace'
    | '/news'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/workspaces'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/$category'
    | '/workspaces/new'
    | '/news/'
    | '/settings/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/migration'
    | '/automations'
    | '/connections'
    | '/marketplace'
    | '/onboarding'
    | '/projects'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/$category'
    | '/workspaces/new'
    | '/news'
    | '/settings'
    | '/workspaces'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/sessions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/migration'
    | '/_app/automations'
    | '/_app/connections'
    | '/_app/marketplace'
    | '/_app/news'
    | '/_app/onboarding'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/workspaces'
    | '/_app/news/$newsId'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/_app/settings/$category'
    | '/_app/workspaces/new'
    | '/_app/news/'
    | '/_app/settings/'
    | '/_app/workspaces/'
    | '/_app/workspaces/$workspaceId/settings'
    | '/_app/workspaces/$workspaceId/'
    | '/_app/workspaces/$workspaceId/sessions/$sessionId'
    | '/_app/workspaces/$workspaceId/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MigrationRoute: typeof MigrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/_app/workspaces/new': {
      id: '/_app/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof AppWorkspacesNewRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/settings/$category': {
      id: '/_app/settings/$category'
      path: '/$category'
      fullPath: '/settings/$category'
      preLoaderRoute: typeof AppSettingsCategoryRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/news/$newsId': {
      id: '/_app/news/$newsId'
      path: '/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof AppNewsNewsIdRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/_app/workspaces/$workspaceId/': {
      id: '/_app/workspaces/$workspaceId/'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/workspaces/$workspaceId/settings': {
      id: '/_app/workspaces/$workspaceId/settings'
      path: '/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/workspaces/$workspaceId/sessions/': {
      id: '/_app/workspaces/$workspaceId/sessions/'
      path: '/$workspaceId/sessions'
      fullPath: '/workspaces/$workspaceId/sessions/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSessionsIndexRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/workspaces/$workspaceId/sessions/$sessionId': {
      id: '/_app/workspaces/$workspaceId/sessions/$sessionId'
      path: '/$workspaceId/sessions/$sessionId'
      fullPath: '/workspaces/$workspaceId/sessions/$sessionId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
  }
}

interface AppNewsRouteChildren {
  AppNewsNewsIdRoute: typeof AppNewsNewsIdRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
}

const AppNewsRouteChildren: AppNewsRouteChildren = {
  AppNewsNewsIdRoute: AppNewsNewsIdRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
}

const AppNewsRouteWithChildren =
  AppNewsRoute._addFileChildren(AppNewsRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsCategoryRoute: typeof AppSettingsCategoryRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsCategoryRoute: AppSettingsCategoryRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWorkspacesRouteChildren {
  AppWorkspacesNewRoute: typeof AppWorkspacesNewRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppWorkspacesWorkspaceIdSettingsRoute: typeof AppWorkspacesWorkspaceIdSettingsRoute
  AppWorkspacesWorkspaceIdIndexRoute: typeof AppWorkspacesWorkspaceIdIndexRoute
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
  AppWorkspacesWorkspaceIdSessionsIndexRoute: typeof AppWorkspacesWorkspaceIdSessionsIndexRoute
}

const AppWorkspacesRouteChildren: AppWorkspacesRouteChildren = {
  AppWorkspacesNewRoute: AppWorkspacesNewRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppWorkspacesWorkspaceIdSettingsRoute: AppWorkspacesWorkspaceIdSettingsRoute,
  AppWorkspacesWorkspaceIdIndexRoute: AppWorkspacesWorkspaceIdIndexRoute,
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute:
    AppWorkspacesWorkspaceIdSessionsSessionIdRoute,
  AppWorkspacesWorkspaceIdSessionsIndexRoute:
    AppWorkspacesWorkspaceIdSessionsIndexRoute,
}

const AppWorkspacesRouteWithChildren = AppWorkspacesRoute._addFileChildren(
  AppWorkspacesRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppNewsRoute: typeof AppNewsRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWorkspacesRoute: typeof AppWorkspacesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppNewsRoute: AppNewsRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWorkspacesRoute: AppWorkspacesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MigrationRoute: MigrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
