/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app/workspaces'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as AppVigiaRouteImport } from './routes/_app/vigia'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppCompanyContextRouteImport } from './routes/_app/company-context'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces.index'
import { Route as AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport } from './routes/_app/workspaces.$workspaceId.sessions.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppVigiaRoute = AppVigiaRouteImport.update({
  id: '/vigia',
  path: '/vigia',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyContextRoute = AppCompanyContextRouteImport.update({
  id: '/company-context',
  path: '/company-context',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspacesRoute,
} as any)
const AppWorkspacesWorkspaceIdSessionsSessionIdRoute =
  AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport.update({
    id: '/$workspaceId/sessions/$sessionId',
    path: '/$workspaceId/sessions/$sessionId',
    getParentRoute: () => AppWorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/company-context': typeof AppCompanyContextRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/news': typeof AppNewsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/sources': typeof AppSourcesRoute
  '/support': typeof AppSupportRoute
  '/vigia': typeof AppVigiaRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workspaces': typeof AppWorkspacesRouteWithChildren
  '/workspaces/': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/company-context': typeof AppCompanyContextRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/news': typeof AppNewsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/sources': typeof AppSourcesRoute
  '/support': typeof AppSupportRoute
  '/vigia': typeof AppVigiaRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/company-context': typeof AppCompanyContextRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/vigia': typeof AppVigiaRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/workspaces': typeof AppWorkspacesRouteWithChildren
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/workspaces/$workspaceId/sessions/$sessionId': typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/company-context'
    | '/marketplace'
    | '/news'
    | '/onboarding'
    | '/projects'
    | '/scheduler'
    | '/settings'
    | '/skills'
    | '/sources'
    | '/support'
    | '/vigia'
    | '/workflows'
    | '/workspaces'
    | '/workspaces/'
    | '/workspaces/$workspaceId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/company-context'
    | '/marketplace'
    | '/news'
    | '/onboarding'
    | '/projects'
    | '/scheduler'
    | '/settings'
    | '/skills'
    | '/sources'
    | '/support'
    | '/vigia'
    | '/workflows'
    | '/workspaces'
    | '/workspaces/$workspaceId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/company-context'
    | '/_app/marketplace'
    | '/_app/news'
    | '/_app/onboarding'
    | '/_app/projects'
    | '/_app/scheduler'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/sources'
    | '/_app/support'
    | '/_app/vigia'
    | '/_app/workflows'
    | '/_app/workspaces'
    | '/_app/workspaces/'
    | '/_app/workspaces/$workspaceId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vigia': {
      id: '/_app/vigia'
      path: '/vigia'
      fullPath: '/vigia'
      preLoaderRoute: typeof AppVigiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company-context': {
      id: '/_app/company-context'
      path: '/company-context'
      fullPath: '/company-context'
      preLoaderRoute: typeof AppCompanyContextRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
    '/_app/workspaces/$workspaceId/sessions/$sessionId': {
      id: '/_app/workspaces/$workspaceId/sessions/$sessionId'
      path: '/$workspaceId/sessions/$sessionId'
      fullPath: '/workspaces/$workspaceId/sessions/$sessionId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRouteImport
      parentRoute: typeof AppWorkspacesRoute
    }
  }
}

interface AppWorkspacesRouteChildren {
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute: typeof AppWorkspacesWorkspaceIdSessionsSessionIdRoute
}

const AppWorkspacesRouteChildren: AppWorkspacesRouteChildren = {
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppWorkspacesWorkspaceIdSessionsSessionIdRoute:
    AppWorkspacesWorkspaceIdSessionsSessionIdRoute,
}

const AppWorkspacesRouteWithChildren = AppWorkspacesRoute._addFileChildren(
  AppWorkspacesRouteChildren,
)

interface AppRouteChildren {
  AppCompanyContextRoute: typeof AppCompanyContextRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppNewsRoute: typeof AppNewsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVigiaRoute: typeof AppVigiaRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCompanyContextRoute: AppCompanyContextRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppNewsRoute: AppNewsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppSupportRoute: AppSupportRoute,
  AppVigiaRoute: AppVigiaRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppWorkspacesRoute: AppWorkspacesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
